name: Deploy to Prefect Cloud

on:
  workflow_run:
    workflows: ["Terraform CI/CD"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Prefect Cloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          # see https://github.com/docker/docker-py/issues/3256 for why we need to pin requests
          # docker-compose is deprecated and doesn't work with newer versions of docker
          uv pip install --system "pyyaml==5.3.1" "requests<2.32.0" "docker==6.1.3" docker-compose
          pip install prefect==2.14.21 prefect-aws==0.4.12 boto3==1.34.30

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AWS_ECR_REGISTRY }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Prefect Auth
        uses: PrefectHQ/actions-prefect-auth@v1
        with:
          prefect-api-key: ${{ secrets.PREFECT_API_KEY }}
          prefect-workspace: ${{ secrets.PREFECT_WORKSPACE }}

      - name: echos
        shell: bash
        run: |
          echo ${{ secrets.PREFECT_API_KEY }}
          echo ${{ secrets.PREFECT_WORKSPACE }}
          echo ${{ secrets.AWS_REGION }}
          echo ${{ secrets.AWS_ECR_REGISTRY }}
          echo ${{ secrets.AWS_ACCESS_KEY_ID }}
          echo ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          prefect block ls
          prefect config view

      # - name: Run Prefect deployment
      #   env:
      #     PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }} # Only needed if using Prefect Cloud
      #   run: |
      #     python -m src.orchestration.deployments
